# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(439, 275)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(69, 100, 291, 141))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(73, 76, 116);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 20px;\n"
"   border-color: rgb(220, 220, 220);\n"
"   border-width : 0px; \n"
"   border-style:inset;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Ok = QtWidgets.QPushButton(self.frame)
        self.Ok.setGeometry(QtCore.QRect(100, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Ok.setFont(font)
        self.Ok.setStyleSheet("QPushButton {\n"
"background-color: rgba(254, 121, 199, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(216, 102, 171);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(168, 80, 133, 255);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.Ok.setObjectName("Ok")
        self.error = QtWidgets.QLabel(self.frame)
        self.error.setGeometry(QtCore.QRect(20, 10, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.error.setFont(font)
        self.error.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-width : 0px;\n"
"border-style:inset;")
        self.error.setObjectName("error")
        self.navibar = QtWidgets.QFrame(Dialog)
        self.navibar.setGeometry(QtCore.QRect(250, 50, 111, 91))
        self.navibar.setStyleSheet("QFrame {\n"
"    background-color: rgb(121, 125, 191);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"rgb(121, 125, 191)")
        self.navibar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navibar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navibar.setObjectName("navibar")
        self.close = QtWidgets.QPushButton(self.navibar)
        self.close.setGeometry(QtCore.QRect(70, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.close.setFont(font)
        self.close.setStyleSheet("QPushButton {\n"
"background-color: rgb(252, 87, 83);\n"
"border-radius: 14.99px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(193, 65, 63);\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(193, 65, 63);\n"
"border-radius: 10.99px;\n"
"}\n"
"")
        self.close.setText("")
        self.close.setObjectName("close")
        self.icona = QtWidgets.QPushButton(self.navibar)
        self.icona.setGeometry(QtCore.QRect(30, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.icona.setFont(font)
        self.icona.setStyleSheet("QPushButton {\n"
"background-color: rgb(253, 188, 64);\n"
"border-radius: 14.99px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(203, 166, 44);\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(203, 166, 44);\n"
"border-radius: 10.99px;\n"
"}\n"
"")
        self.icona.setText("")
        self.icona.setObjectName("icona")
        self.titlebar = QtWidgets.QFrame(Dialog)
        self.titlebar.setGeometry(QtCore.QRect(70, 50, 251, 91))
        self.titlebar.setStyleSheet("QFrame {\n"
"    background-color: rgb(121, 125, 191);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"rgb(121, 125, 191)")
        self.titlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar.setObjectName("titlebar")
        self.label_2 = QtWidgets.QLabel(self.titlebar)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.titlebar)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/75-758794_windows-8-error-icon-download-sign-hd-png.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.titlebar.raise_()
        self.navibar.raise_()
        self.frame.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Ok.setText(_translate("Dialog", "Ok"))
        self.error.setText(_translate("Dialog", "<Text>"))
        self.label_2.setText(_translate("Dialog", "SynMax"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
