# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitledpages.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(597, 528)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SplashScreen.sizePolicy().hasHeightForWidth())
        SplashScreen.setSizePolicy(sizePolicy)
        SplashScreen.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        SplashScreen.setFont(font)
        SplashScreen.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.titlebar = QtWidgets.QFrame(self.centralwidget)
        self.titlebar.setGeometry(QtCore.QRect(0, 0, 411, 91))
        self.titlebar.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(25, 86, 155, 255), stop:1 rgba(48, 183, 233, 255));\n"
"    border-radius: 20px;\n"
"   \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"")
        self.titlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar.setObjectName("titlebar")
        self.label_2 = QtWidgets.QLabel(self.titlebar)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;")
        self.label_2.setObjectName("label_2")
        self.navibar = QtWidgets.QFrame(self.centralwidget)
        self.navibar.setGeometry(QtCore.QRect(420, 0, 171, 91))
        self.navibar.setStyleSheet("QFrame {\n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(48, 183, 233, 255), stop:1 rgba(25, 86, 155, 255));\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"rgb(121, 125, 191)")
        self.navibar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navibar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navibar.setObjectName("navibar")
        self.close = QtWidgets.QPushButton(self.navibar)
        self.close.setGeometry(QtCore.QRect(20, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.close.setFont(font)
        self.close.setStyleSheet("QPushButton {\n"
"background-color: rgb(252, 87, 83);\n"
"border-radius: 14.99px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(193, 65, 63);\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(193, 65, 63);\n"
"border-radius: 10.99px;\n"
"}\n"
"")
        self.close.setText("")
        self.close.setObjectName("close")
        self.icona = QtWidgets.QPushButton(self.navibar)
        self.icona.setGeometry(QtCore.QRect(120, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.icona.setFont(font)
        self.icona.setStyleSheet("QPushButton {\n"
"background-color: rgb(253, 188, 64);\n"
"border-radius: 14.99px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(203, 166, 44);\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(203, 166, 44);\n"
"border-radius: 10.99px;\n"
"}\n"
"")
        self.icona.setText("")
        self.icona.setObjectName("icona")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 50, 591, 471))
        self.stackedWidget.setStatusTip("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(0, 0, 591, 471))
        self.frame.setStyleSheet("QFrame {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.0284091, y1:1, x2:1, y2:0, stop:0 rgba(25, 86, 155, 255), stop:1 rgba(48, 183, 233, 255));\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 20px;\n"
"}")
        self.frame.setObjectName("frame")
        self.url = QtWidgets.QLabel(self.frame)
        self.url.setGeometry(QtCore.QRect(0, 30, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(28)
        self.url.setFont(font)
        self.url.setStyleSheet("background-color: none;")
        self.url.setAlignment(QtCore.Qt.AlignCenter)
        self.url.setObjectName("url")
        self.finder = QtWidgets.QPushButton(self.frame)
        self.finder.setGeometry(QtCore.QRect(410, 150, 70, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.finder.setFont(font)
        self.finder.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.finder.setObjectName("finder")
        self.searchbar = QtWidgets.QLineEdit(self.frame)
        self.searchbar.setGeometry(QtCore.QRect(120, 120, 361, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.searchbar.setFont(font)
        self.searchbar.setStyleSheet("background-color: rgb(214, 214, 214);\n"
"color : rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.searchbar.setText("")
        self.searchbar.setAlignment(QtCore.Qt.AlignCenter)
        self.searchbar.setObjectName("searchbar")
        self.urlplaylist = QtWidgets.QLabel(self.frame)
        self.urlplaylist.setGeometry(QtCore.QRect(0, 200, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(28)
        self.urlplaylist.setFont(font)
        self.urlplaylist.setStyleSheet("background-color: none;")
        self.urlplaylist.setAlignment(QtCore.Qt.AlignCenter)
        self.urlplaylist.setObjectName("urlplaylist")
        self.searchbar_p = QtWidgets.QLineEdit(self.frame)
        self.searchbar_p.setGeometry(QtCore.QRect(120, 290, 361, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.searchbar_p.setFont(font)
        self.searchbar_p.setStyleSheet("background-color: rgb(214, 214, 214);\n"
"color : rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.searchbar_p.setText("")
        self.searchbar_p.setAlignment(QtCore.Qt.AlignCenter)
        self.searchbar_p.setObjectName("searchbar_p")
        self.finder_p = QtWidgets.QPushButton(self.frame)
        self.finder_p.setGeometry(QtCore.QRect(410, 320, 70, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.finder_p.setFont(font)
        self.finder_p.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.finder_p.setObjectName("finder_p")
        self.loading = QtWidgets.QLabel(self.frame)
        self.loading.setGeometry(QtCore.QRect(70, 450, 411, 261))
        self.loading.setStyleSheet("background-color: none;")
        self.loading.setText("")
        self.loading.setPixmap(QtGui.QPixmap("Mesmerizing Geometric GIFs by Florian de Looij _ Inspiration Grid.gif"))
        self.loading.setObjectName("loading")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Step1 = QtWidgets.QFrame(self.page_2)
        self.Step1.setEnabled(True)
        self.Step1.setGeometry(QtCore.QRect(0, 0, 591, 471))
        self.Step1.setStyleSheet("QFrame {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.0284091, y1:1, x2:1, y2:0, stop:0 rgba(25, 86, 155, 255), stop:1 rgba(48, 183, 233, 255));\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 20px;\n"
"}")
        self.Step1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Step1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Step1.setObjectName("Step1")
        self.thumbnail = QtWidgets.QLabel(self.Step1)
        self.thumbnail.setGeometry(QtCore.QRect(180, 20, 231, 153))
        self.thumbnail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 29px;")
        self.thumbnail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thumbnail.setText("")
        self.thumbnail.setPixmap(QtGui.QPixmap("../../../../.designer/backup/tbls/thunbail.jpg"))
        self.thumbnail.setScaledContents(True)
        self.thumbnail.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnail.setWordWrap(False)
        self.thumbnail.setOpenExternalLinks(False)
        self.thumbnail.setObjectName("thumbnail")
        self.ytitle = QtWidgets.QLabel(self.Step1)
        self.ytitle.setGeometry(QtCore.QRect(10, 180, 571, 121))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.ytitle.setFont(font)
        self.ytitle.setStyleSheet("background-color: none;")
        self.ytitle.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ytitle.setText("ereeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")
        self.ytitle.setTextFormat(QtCore.Qt.AutoText)
        self.ytitle.setScaledContents(True)
        self.ytitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ytitle.setWordWrap(False)
        self.ytitle.setIndent(-1)
        self.ytitle.setOpenExternalLinks(False)
        self.ytitle.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.ytitle.setObjectName("ytitle")
        self.ytime = QtWidgets.QLabel(self.Step1)
        self.ytime.setGeometry(QtCore.QRect(0, 10, 201, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.ytime.setFont(font)
        self.ytime.setStyleSheet("background-color: none;")
        self.ytime.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ytime.setObjectName("ytime")
        self.ytauthor = QtWidgets.QLabel(self.Step1)
        self.ytauthor.setGeometry(QtCore.QRect(370, 10, 201, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.ytauthor.setFont(font)
        self.ytauthor.setStyleSheet("background-color: none;")
        self.ytauthor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.ytauthor.setObjectName("ytauthor")
        self.description = QtWidgets.QLabel(self.Step1)
        self.description.setGeometry(QtCore.QRect(10, 310, 571, 111))
        self.description.setStyleSheet("background-color: none;")
        self.description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.description.setObjectName("description")
        self.finder_p_2 = QtWidgets.QPushButton(self.Step1)
        self.finder_p_2.setGeometry(QtCore.QRect(370, 420, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.finder_p_2.setFont(font)
        self.finder_p_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.finder_p_2.setCheckable(False)
        self.finder_p_2.setAutoDefault(False)
        self.finder_p_2.setObjectName("finder_p_2")
        self.finder_p_3 = QtWidgets.QPushButton(self.Step1)
        self.finder_p_3.setGeometry(QtCore.QRect(10, 420, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.finder_p_3.setFont(font)
        self.finder_p_3.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.finder_p_3.setObjectName("finder_p_3")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.Step2 = QtWidgets.QFrame(self.page_3)
        self.Step2.setEnabled(True)
        self.Step2.setGeometry(QtCore.QRect(0, 0, 591, 471))
        self.Step2.setStyleSheet("QFrame {\n"
"        background-color: qlineargradient(spread:pad, x1:0.0284091, y1:1, x2:1, y2:0, stop:0 rgba(25, 86, 155, 255), stop:1 rgba(48, 183, 233, 255));\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Step2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Step2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Step2.setObjectName("Step2")
        self.label_5 = QtWidgets.QLabel(self.Step2)
        self.label_5.setGeometry(QtCore.QRect(90, 10, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.thumbnai2 = QtWidgets.QLabel(self.Step2)
        self.thumbnai2.setGeometry(QtCore.QRect(20, 50, 165, 109))
        self.thumbnai2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 29px;")
        self.thumbnai2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thumbnai2.setText("")
        self.thumbnai2.setPixmap(QtGui.QPixmap("../../../../.designer/backup/tbls/thunbail.jpg"))
        self.thumbnai2.setScaledContents(True)
        self.thumbnai2.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnai2.setWordWrap(False)
        self.thumbnai2.setOpenExternalLinks(False)
        self.thumbnai2.setObjectName("thumbnai2")
        self.vidname_2 = QtWidgets.QLabel(self.Step2)
        self.vidname_2.setGeometry(QtCore.QRect(190, 50, 371, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.vidname_2.setFont(font)
        self.vidname_2.setStyleSheet("background-color: none;")
        self.vidname_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.vidname_2.setText("ereeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")
        self.vidname_2.setScaledContents(True)
        self.vidname_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.vidname_2.setWordWrap(False)
        self.vidname_2.setIndent(-1)
        self.vidname_2.setOpenExternalLinks(False)
        self.vidname_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.vidname_2.setObjectName("vidname_2")
        self.label_7 = QtWidgets.QLabel(self.Step2)
        self.label_7.setGeometry(QtCore.QRect(130, 170, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.Filebar = QtWidgets.QLineEdit(self.Step2)
        self.Filebar.setGeometry(QtCore.QRect(130, 210, 341, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.Filebar.setFont(font)
        self.Filebar.setStyleSheet("background-color: rgb(214, 214, 214);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.Filebar.setText("")
        self.Filebar.setObjectName("Filebar")
        self.defay = QtWidgets.QPushButton(self.Step2)
        self.defay.setGeometry(QtCore.QRect(130, 240, 111, 41))
        self.defay.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.defay.setObjectName("defay")
        self.pushButton_7 = QtWidgets.QPushButton(self.Step2)
        self.pushButton_7.setGeometry(QtCore.QRect(360, 240, 111, 41))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_8 = QtWidgets.QLabel(self.Step2)
        self.label_8.setGeometry(QtCore.QRect(130, 300, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.FileLocName = QtWidgets.QLineEdit(self.Step2)
        self.FileLocName.setGeometry(QtCore.QRect(130, 340, 351, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.FileLocName.setFont(font)
        self.FileLocName.setStyleSheet("background-color: rgb(214, 214, 214);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.FileLocName.setText("")
        self.FileLocName.setObjectName("FileLocName")
        self.findfoldr = QtWidgets.QPushButton(self.Step2)
        self.findfoldr.setGeometry(QtCore.QRect(490, 340, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.findfoldr.setFont(font)
        self.findfoldr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.findfoldr.setStyleSheet("background-color: rgb(214, 214, 214);\n"
"color : rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"qproperty-alignment: AlignCenter;")
        self.findfoldr.setText("...")
        self.findfoldr.setObjectName("findfoldr")
        self.pushButton_8 = QtWidgets.QPushButton(self.Step2)
        self.pushButton_8.setGeometry(QtCore.QRect(130, 370, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.finder_p_5 = QtWidgets.QPushButton(self.Step2)
        self.finder_p_5.setGeometry(QtCore.QRect(370, 420, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.finder_p_5.setFont(font)
        self.finder_p_5.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.finder_p_5.setCheckable(False)
        self.finder_p_5.setAutoDefault(False)
        self.finder_p_5.setObjectName("finder_p_5")
        self.finder_p_4 = QtWidgets.QPushButton(self.Step2)
        self.finder_p_4.setGeometry(QtCore.QRect(10, 420, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.finder_p_4.setFont(font)
        self.finder_p_4.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.finder_p_4.setObjectName("finder_p_4")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.Step2_2 = QtWidgets.QFrame(self.page_4)
        self.Step2_2.setEnabled(True)
        self.Step2_2.setGeometry(QtCore.QRect(0, 0, 591, 471))
        self.Step2_2.setStyleSheet("QFrame {\n"
"        background-color: qlineargradient(spread:pad, x1:0.0284091, y1:1, x2:1, y2:0, stop:0 rgba(25, 86, 155, 255), stop:1 rgba(48, 183, 233, 255));\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.Step2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Step2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Step2_2.setObjectName("Step2_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.Step2_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 420, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.Step2_2)
        self.pushButton_6.setGeometry(QtCore.QRect(370, 420, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_6 = QtWidgets.QLabel(self.Step2_2)
        self.label_6.setGeometry(QtCore.QRect(100, 0, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.thumbnail_4 = QtWidgets.QLabel(self.Step2_2)
        self.thumbnail_4.setGeometry(QtCore.QRect(20, 50, 165, 109))
        self.thumbnail_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 29px;")
        self.thumbnail_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thumbnail_4.setText("")
        self.thumbnail_4.setPixmap(QtGui.QPixmap("../../../../.designer/backup/tbls/thunbail.jpg"))
        self.thumbnail_4.setScaledContents(True)
        self.thumbnail_4.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnail_4.setWordWrap(False)
        self.thumbnail_4.setOpenExternalLinks(False)
        self.thumbnail_4.setObjectName("thumbnail_4")
        self.VideoSize_2 = QtWidgets.QLabel(self.Step2_2)
        self.VideoSize_2.setGeometry(QtCore.QRect(480, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.VideoSize_2.setFont(font)
        self.VideoSize_2.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.VideoSize_2.setObjectName("VideoSize_2")
        self.vidname_3 = QtWidgets.QLabel(self.Step2_2)
        self.vidname_3.setGeometry(QtCore.QRect(190, 50, 371, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.vidname_3.setFont(font)
        self.vidname_3.setStyleSheet("background-color: none;")
        self.vidname_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.vidname_3.setText("ereeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")
        self.vidname_3.setScaledContents(True)
        self.vidname_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.vidname_3.setWordWrap(False)
        self.vidname_3.setIndent(-1)
        self.vidname_3.setOpenExternalLinks(False)
        self.vidname_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.vidname_3.setObjectName("vidname_3")
        self.label_9 = QtWidgets.QLabel(self.Step2_2)
        self.label_9.setGeometry(QtCore.QRect(130, 170, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.MP4 = QtWidgets.QRadioButton(self.Step2_2)
        self.MP4.setGeometry(QtCore.QRect(230, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(20)
        self.MP4.setFont(font)
        self.MP4.setStyleSheet("color : rgb(255, 255, 255);")
        self.MP4.setIconSize(QtCore.QSize(19, 16))
        self.MP4.setObjectName("MP4")
        self.buttonGroup = QtWidgets.QButtonGroup(SplashScreen)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.MP4)
        self.AVI = QtWidgets.QRadioButton(self.Step2_2)
        self.AVI.setGeometry(QtCore.QRect(330, 220, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(20)
        self.AVI.setFont(font)
        self.AVI.setStyleSheet("color : rgb(255, 255, 255);")
        self.AVI.setIconSize(QtCore.QSize(19, 16))
        self.AVI.setObjectName("AVI")
        self.buttonGroup.addButton(self.AVI)
        self.MP3 = QtWidgets.QRadioButton(self.Step2_2)
        self.MP3.setGeometry(QtCore.QRect(130, 220, 82, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(20)
        self.MP3.setFont(font)
        self.MP3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Segoe UI Symbol\";")
        self.MP3.setIconSize(QtCore.QSize(19, 16))
        self.MP3.setObjectName("MP3")
        self.buttonGroup.addButton(self.MP3)
        self.label_10 = QtWidgets.QLabel(self.Step2_2)
        self.label_10.setGeometry(QtCore.QRect(130, 260, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.Low = QtWidgets.QRadioButton(self.Step2_2)
        self.Low.setGeometry(QtCore.QRect(130, 320, 111, 51))
        self.Low.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Segoe UI Symbol\";")
        self.Low.setObjectName("Low")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(SplashScreen)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.Low)
        self.High = QtWidgets.QRadioButton(self.Step2_2)
        self.High.setGeometry(QtCore.QRect(270, 320, 111, 51))
        self.High.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Segoe UI Symbol\";")
        self.High.setObjectName("High")
        self.buttonGroup_2.addButton(self.High)
        self.Custom = QtWidgets.QRadioButton(self.Step2_2)
        self.Custom.setGeometry(QtCore.QRect(410, 320, 111, 51))
        self.Custom.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Segoe UI Symbol\";")
        self.Custom.setObjectName("Custom")
        self.buttonGroup_2.addButton(self.Custom)
        self.qts = QtWidgets.QLabel(self.Step2_2)
        self.qts.setGeometry(QtCore.QRect(320, 390, 47, 13))
        self.qts.setStyleSheet("background-color: none;\n"
"color: none;")
        self.qts.setObjectName("qts")
        self.qts_2 = QtWidgets.QLabel(self.Step2_2)
        self.qts_2.setGeometry(QtCore.QRect(380, 390, 47, 13))
        self.qts_2.setStyleSheet("background-color: none;\n"
"color: none;")
        self.qts_2.setObjectName("qts_2")
        self.CustomQ = QtWidgets.QLineEdit(self.Step2_2)
        self.CustomQ.setGeometry(QtCore.QRect(440, 370, 71, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.CustomQ.setFont(font)
        self.CustomQ.setStyleSheet("background-color: rgb(214, 214, 214);\n"
"color : rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.CustomQ.setText("")
        self.CustomQ.setObjectName("CustomQ")
        self.loading_2 = QtWidgets.QLabel(self.Step2_2)
        self.loading_2.setGeometry(QtCore.QRect(100, 460, 411, 261))
        self.loading_2.setStyleSheet("background-color: none;")
        self.loading_2.setText("")
        self.loading_2.setPixmap(QtGui.QPixmap("Mesmerizing Geometric GIFs by Florian de Looij _ Inspiration Grid.gif"))
        self.loading_2.setObjectName("loading_2")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.frame_2 = QtWidgets.QFrame(self.page_5)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 591, 471))
        self.frame_2.setStyleSheet("QFrame {\n"
"        background-color: qlineargradient(spread:pad, x1:0.0284091, y1:1, x2:1, y2:0, stop:0 rgba(25, 86, 155, 255), stop:1 rgba(48, 183, 233, 255));\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame_2.setObjectName("frame_2")
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setGeometry(QtCore.QRect(38, 260, 531, 59))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color: rgb(255, 255, 255);\n"
" color: rgb(200, 200, 200);\n"
"  border-style: none;\n"
"  border-radius: 23px;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"border-radius : 23;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(251, 108, 108, 255), stop:1 rgba(61, 188, 254, 255));\n"
"}\n"
"")
        self.progressBar.setProperty("value", 9)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.finder_p_8 = QtWidgets.QPushButton(self.frame_2)
        self.finder_p_8.setGeometry(QtCore.QRect(10, 420, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.finder_p_8.setFont(font)
        self.finder_p_8.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.finder_p_8.setObjectName("finder_p_8")
        self.VideoSize_3 = QtWidgets.QLabel(self.frame_2)
        self.VideoSize_3.setGeometry(QtCore.QRect(470, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.VideoSize_3.setFont(font)
        self.VideoSize_3.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.VideoSize_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VideoSize_3.setObjectName("VideoSize_3")
        self.VideoSize_4 = QtWidgets.QLabel(self.frame_2)
        self.VideoSize_4.setGeometry(QtCore.QRect(40, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.VideoSize_4.setFont(font)
        self.VideoSize_4.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.VideoSize_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.VideoSize_4.setObjectName("VideoSize_4")
        self.VideoSize_5 = QtWidgets.QLabel(self.frame_2)
        self.VideoSize_5.setGeometry(QtCore.QRect(450, 320, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.VideoSize_5.setFont(font)
        self.VideoSize_5.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.VideoSize_5.setAlignment(QtCore.Qt.AlignCenter)
        self.VideoSize_5.setObjectName("VideoSize_5")
        self.label_11 = QtWidgets.QLabel(self.page_5)
        self.label_11.setGeometry(QtCore.QRect(30, 0, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_5)
        self.label_12.setGeometry(QtCore.QRect(70, 30, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(21)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.frame_3 = QtWidgets.QFrame(self.page_6)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 591, 471))
        self.frame_3.setStyleSheet("QFrame {\n"
"        background-color: qlineargradient(spread:pad, x1:0.0284091, y1:1, x2:1, y2:0, stop:0 rgba(25, 86, 155, 255), stop:1 rgba(48, 183, 233, 255));\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame_3.setObjectName("frame_3")
        self.VideoSize_7 = QtWidgets.QLabel(self.frame_3)
        self.VideoSize_7.setGeometry(QtCore.QRect(0, 0, 591, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(50)
        self.VideoSize_7.setFont(font)
        self.VideoSize_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.VideoSize_7.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.VideoSize_7.setAlignment(QtCore.Qt.AlignCenter)
        self.VideoSize_7.setObjectName("VideoSize_7")
        self.VideoSize_8 = QtWidgets.QLabel(self.frame_3)
        self.VideoSize_8.setGeometry(QtCore.QRect(0, 70, 591, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(30)
        self.VideoSize_8.setFont(font)
        self.VideoSize_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.VideoSize_8.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.VideoSize_8.setAlignment(QtCore.Qt.AlignCenter)
        self.VideoSize_8.setObjectName("VideoSize_8")
        self.openfilebutton = QtWidgets.QPushButton(self.frame_3)
        self.openfilebutton.setGeometry(QtCore.QRect(100, 170, 361, 58))
        self.openfilebutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(39)
        self.openfilebutton.setFont(font)
        self.openfilebutton.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.openfilebutton.setObjectName("openfilebutton")
        self.openfilefolder = QtWidgets.QPushButton(self.frame_3)
        self.openfilefolder.setGeometry(QtCore.QRect(130, 240, 311, 58))
        self.openfilefolder.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.openfilefolder.setFont(font)
        self.openfilefolder.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.openfilefolder.setObjectName("openfilefolder")
        self.retrunpage1 = QtWidgets.QPushButton(self.frame_3)
        self.retrunpage1.setGeometry(QtCore.QRect(160, 310, 255, 58))
        self.retrunpage1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.retrunpage1.setFont(font)
        self.retrunpage1.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.retrunpage1.setObjectName("retrunpage1")
        self.closesynmax = QtWidgets.QPushButton(self.frame_3)
        self.closesynmax.setGeometry(QtCore.QRect(190, 380, 205, 50))
        self.closesynmax.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.closesynmax.setFont(font)
        self.closesynmax.setStyleSheet("QPushButton {\n"
"background-color: rgb(158, 203, 255);\n"
"color: rgb(255, 255,255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" \n"
"    \n"
"    background-color: rgb(143, 184, 231);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(126, 162, 203);\n"
"color: rgb(204, 204, 204);\n"
"\n"
"}")
        self.closesynmax.setObjectName("closesynmax")
        self.stackedWidget.addWidget(self.page_6)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "SynMax Video Downloader 1.0"))
        self.label_2.setText(_translate("SplashScreen", "SymMax Video Downloader 1.0"))
        self.url.setText(_translate("SplashScreen", "YouTube Video Link:"))
        self.finder.setText(_translate("SplashScreen", "Find"))
        self.urlplaylist.setText(_translate("SplashScreen", "YouTube Playlist Link:"))
        self.finder_p.setText(_translate("SplashScreen", "Find"))
        self.ytime.setText(_translate("SplashScreen", "Length"))
        self.ytauthor.setText(_translate("SplashScreen", "Author"))
        self.description.setText(_translate("SplashScreen", "TextLabel"))
        self.finder_p_2.setText(_translate("SplashScreen", "Next"))
        self.finder_p_3.setText(_translate("SplashScreen", "Cancel"))
        self.Step2.setToolTip(_translate("SplashScreen", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("SplashScreen", "Select Directory And File Name"))
        self.label_7.setText(_translate("SplashScreen", "File Name"))
        self.defay.setText(_translate("SplashScreen", "Default"))
        self.pushButton_7.setText(_translate("SplashScreen", "Random"))
        self.label_8.setText(_translate("SplashScreen", "File Location"))
        self.pushButton_8.setText(_translate("SplashScreen", "Default"))
        self.finder_p_5.setText(_translate("SplashScreen", "Next"))
        self.finder_p_4.setText(_translate("SplashScreen", "Cancel"))
        self.Step2_2.setToolTip(_translate("SplashScreen", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_5.setText(_translate("SplashScreen", "Cancel"))
        self.pushButton_6.setText(_translate("SplashScreen", "Download"))
        self.label_6.setText(_translate("SplashScreen", "      Select Download Types"))
        self.VideoSize_2.setText(_translate("SplashScreen", "Size"))
        self.label_9.setText(_translate("SplashScreen", "File Name"))
        self.MP4.setText(_translate("SplashScreen", "mp4"))
        self.AVI.setText(_translate("SplashScreen", "avi"))
        self.MP3.setText(_translate("SplashScreen", "mp3"))
        self.label_10.setText(_translate("SplashScreen", "File Name"))
        self.Low.setText(_translate("SplashScreen", "<Low>"))
        self.High.setText(_translate("SplashScreen", "<High>"))
        self.Custom.setText(_translate("SplashScreen", "Custom"))
        self.qts.setText(_translate("SplashScreen", "Format"))
        self.qts_2.setText(_translate("SplashScreen", "Quality"))
        self.finder_p_8.setText(_translate("SplashScreen", "Stop"))
        self.VideoSize_3.setText(_translate("SplashScreen", "Size"))
        self.VideoSize_4.setText(_translate("SplashScreen", "Loaded"))
        self.VideoSize_5.setText(_translate("SplashScreen", "%25"))
        self.label_11.setText(_translate("SplashScreen", "Video.format"))
        self.label_12.setText(_translate("SplashScreen", "Quality"))
        self.VideoSize_7.setText(_translate("SplashScreen", "DOWNLOADED"))
        self.VideoSize_8.setText(_translate("SplashScreen", "THANKS FOR USİNG SYNMAX"))
        self.openfilebutton.setText(_translate("SplashScreen", "OPEN FILE"))
        self.openfilefolder.setText(_translate("SplashScreen", "OPEN FILE FOLDER"))
        self.retrunpage1.setText(_translate("SplashScreen", "MAIN MENU"))
        self.closesynmax.setText(_translate("SplashScreen", "CLOSE SYNMAX"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
